// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../../../BaseClient.js";
import { ForecastClient } from "../resources/forecast/client/Client.js";

export declare namespace PastClient {
    export type Options = BaseClientOptions;
}

export class PastClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<PastClient.Options>;
    protected _forecast: ForecastClient | undefined;

    constructor(options: PastClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get forecast(): ForecastClient {
        return (this._forecast ??= new ForecastClient(this._options));
    }
}
