// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../../../BaseClient.js";
import { Forecast } from "../resources/forecast/client/Client.js";

export declare namespace Past {
    export interface Options extends BaseClientOptions {}
}

export class Past {
    protected readonly _options: Past.Options;
    protected _forecast: Forecast | undefined;

    constructor(_options: Past.Options = {}) {
        this._options = _options;
    }

    public get forecast(): Forecast {
        return (this._forecast ??= new Forecast(this._options));
    }
}
