// This file was auto-generated by Fern from our API Definition.

import type * as Earth from "../../../../../../../../../../index.js";

/**
 * @example
 *     {
 *         latitude: 47.6061,
 *         longitude: -122.3328,
 *         time: "2024-01-01T00:00:00Z",
 *         timezone: "local",
 *         units: "metric"
 *     }
 */
export interface RegionalUsaRequest {
    latitude: number;
    longitude: number;
    time: string;
    timezone?: Earth.Timezone;
    units?: Earth.Units;
}
