// This file was auto-generated by Fern from our API Definition.

import type * as Earth from "../../../../../../index.js";

/**
 * @example
 *     {
 *         time: "2024-01-15T09:30:00Z",
 *         max_lead_time: "max_lead_time",
 *         model: "OFCL"
 *     }
 */
export interface ForecastsTrackRequest {
    /** *Default value: (current time) - Default time zone: UTC* */
    time?: string;
    /** *Value must be > P0D* */
    max_lead_time?: string;
    model?: Earth.ModelName;
}
