/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Earth from "../../../../../../index";

/**
 * @example
 *     {}
 */
export interface ForecastsTrackRequest {
    /**
     * *Default value: (current time) - Default time zone: UTC*
     */
    time?: string;
    model?: Earth.ModelName;
}
