// This file was auto-generated by Fern from our API Definition.

import type * as Earth from "../../../../../../index.js";

/**
 * @example
 *     {
 *         time: "2024-01-15T09:30:00Z",
 *         min_storm_category: 1,
 *         basin_ids: ["basin_ids"],
 *         model: "OFCL"
 *     }
 */
export interface ForecastsListRequest {
    /** *Default value: (current time) - Default time zone: UTC* */
    time?: string;
    min_storm_category?: number;
    basin_ids?: string | string[];
    model?: Earth.cyclones.ForecastsListRequestModel;
}
