// This file was auto-generated by Fern from our API Definition.

import { EarthClient } from "../../../../src/Client";
import { mockServerPool } from "../../../mock-server/MockServerPool";

describe("Personalized", () => {
    test("total-energies", async () => {
        const server = mockServerPool.createServer();
        const client = new EarthClient({ apiKey: "test", environment: server.baseUrl });

        server.mockEndpoint().get("/experimental/personalized/total-energies").respondWith().statusCode(200).build();

        const response = await client.weather.experimental.personalized.totalEnergies();
        expect(response).toEqual(undefined);
    });
});
