// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../../../../../core/headers.js";
import * as core from "../../../../../../../../core/index.js";
import * as environments from "../../../../../../../../environments.js";
import * as errors from "../../../../../../../../errors/index.js";
import * as Earth from "../../../../../../../index.js";

export declare namespace Forecast {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class Forecast {
    protected readonly _options: Forecast.Options;

    constructor(_options: Forecast.Options = {}) {
        this._options = _options;
    }

    /**
     * Get daily weather forecast for a specific location and time
     *
     * @param {Earth.weather.past.ForecastDailyRequest} request
     * @param {Forecast.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Earth.UnprocessableEntityError}
     *
     * @example
     *     await client.weather.past.forecast.daily({
     *         latitude: 47.6061,
     *         longitude: -122.3328,
     *         time: "2024-01-01T00:00:00Z",
     *         timezone: "local",
     *         units: "metric"
     *     })
     */
    public daily(
        request: Earth.weather.past.ForecastDailyRequest,
        requestOptions?: Forecast.RequestOptions,
    ): core.HttpResponsePromise<Earth.DailyWeatherResponse> {
        return core.HttpResponsePromise.fromPromise(this.__daily(request, requestOptions));
    }

    private async __daily(
        request: Earth.weather.past.ForecastDailyRequest,
        requestOptions?: Forecast.RequestOptions,
    ): Promise<core.WithRawResponse<Earth.DailyWeatherResponse>> {
        const { latitude, longitude, time, timezone, units } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams.latitude = latitude.toString();
        _queryParams.longitude = longitude.toString();
        _queryParams.time = time;
        if (timezone != null) {
            _queryParams.timezone = timezone;
        }

        if (units != null) {
            _queryParams.units = units;
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.EarthEnvironment.Production,
                "past/forecast/daily",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Earth.DailyWeatherResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Earth.UnprocessableEntityError(
                        _response.error.body as Earth.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.EarthError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.EarthError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.EarthTimeoutError("Timeout exceeded when calling GET /past/forecast/daily.");
            case "unknown":
                throw new errors.EarthError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get hourly weather forecast for a specific location and time
     *
     * @param {Earth.weather.past.ForecastHourlyRequest} request
     * @param {Forecast.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Earth.UnprocessableEntityError}
     *
     * @example
     *     await client.weather.past.forecast.hourly({
     *         latitude: 47.6061,
     *         longitude: -122.3328,
     *         time: "2024-01-01T00:00:00Z",
     *         timezone: "local",
     *         units: "metric"
     *     })
     */
    public hourly(
        request: Earth.weather.past.ForecastHourlyRequest,
        requestOptions?: Forecast.RequestOptions,
    ): core.HttpResponsePromise<Earth.HourlyWeatherResponse> {
        return core.HttpResponsePromise.fromPromise(this.__hourly(request, requestOptions));
    }

    private async __hourly(
        request: Earth.weather.past.ForecastHourlyRequest,
        requestOptions?: Forecast.RequestOptions,
    ): Promise<core.WithRawResponse<Earth.HourlyWeatherResponse>> {
        const { latitude, longitude, time, timezone, units } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams.latitude = latitude.toString();
        _queryParams.longitude = longitude.toString();
        _queryParams.time = time;
        if (timezone != null) {
            _queryParams.timezone = timezone;
        }

        if (units != null) {
            _queryParams.units = units;
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.EarthEnvironment.Production,
                "past/forecast/hourly",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Earth.HourlyWeatherResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Earth.UnprocessableEntityError(
                        _response.error.body as Earth.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.EarthError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.EarthError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.EarthTimeoutError("Timeout exceeded when calling GET /past/forecast/hourly.");
            case "unknown":
                throw new errors.EarthError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders(): Promise<Record<string, string | undefined>> {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { "X-API-KEY": apiKeyValue };
    }
}
