/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import { Forecast } from "../resources/forecast/client/Client";
import { Experimental } from "../resources/experimental/client/Client";
import { Past } from "../resources/past/client/Client";

export declare namespace Weather {
    export interface Options {
        environment?: core.Supplier<environments.EarthEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey: core.Supplier<string>;
    }
}

export class Weather {
    protected _forecast: Forecast | undefined;
    protected _experimental: Experimental | undefined;
    protected _past: Past | undefined;

    constructor(protected readonly _options: Weather.Options) {}

    public get forecast(): Forecast {
        return (this._forecast ??= new Forecast(this._options));
    }

    public get experimental(): Experimental {
        return (this._experimental ??= new Experimental(this._options));
    }

    public get past(): Past {
        return (this._past ??= new Past(this._options));
    }
}
