// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import * as Earth from "../../../index.js";

export declare namespace Portfolios {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class Portfolios {
    protected readonly _options: Portfolios.Options;

    constructor(_options: Portfolios.Options = {}) {
        this._options = _options;
    }

    /**
     * Return a GeoJSON FeatureCollection of features for a portfolio.
     *
     * @param {string} portfolioId
     * @param {Earth.PortfoliosFeaturesRequest} request
     * @param {Portfolios.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Earth.UnprocessableEntityError}
     *
     * @example
     *     await client.portfolios.features("portfolio_id", {
     *         x: 1,
     *         y: 1,
     *         z: 1,
     *         country: "country"
     *     })
     */
    public features(
        portfolioId: string,
        request: Earth.PortfoliosFeaturesRequest = {},
        requestOptions?: Portfolios.RequestOptions,
    ): core.HttpResponsePromise<Earth.FeatureCollection> {
        return core.HttpResponsePromise.fromPromise(this.__features(portfolioId, request, requestOptions));
    }

    private async __features(
        portfolioId: string,
        request: Earth.PortfoliosFeaturesRequest = {},
        requestOptions?: Portfolios.RequestOptions,
    ): Promise<core.WithRawResponse<Earth.FeatureCollection>> {
        const { x, y, z, country } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (x != null) {
            _queryParams.x = x.toString();
        }

        if (y != null) {
            _queryParams.y = y.toString();
        }

        if (z != null) {
            _queryParams.z = z.toString();
        }

        if (country != null) {
            _queryParams.country = country;
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.EarthEnvironment.Production,
                `portfolios/${core.url.encodePathParam(portfolioId)}/features`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Earth.FeatureCollection, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Earth.UnprocessableEntityError(
                        _response.error.body as Earth.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.EarthError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.EarthError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.EarthTimeoutError(
                    "Timeout exceeded when calling GET /portfolios/{portfolio_id}/features.",
                );
            case "unknown":
                throw new errors.EarthError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Return a GeoJSON FeatureCollection of forecasts for a portfolio.
     *
     * @param {string} portfolioId
     * @param {Earth.PortfoliosForecastsRequest} request
     * @param {Portfolios.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Earth.UnprocessableEntityError}
     *
     * @example
     *     await client.portfolios.forecasts("portfolio_id", {
     *         init_time: "2024-01-15T09:30:00Z"
     *     })
     */
    public forecasts(
        portfolioId: string,
        request: Earth.PortfoliosForecastsRequest,
        requestOptions?: Portfolios.RequestOptions,
    ): core.HttpResponsePromise<Earth.TimeSeriesFeatureCollectionModel> {
        return core.HttpResponsePromise.fromPromise(this.__forecasts(portfolioId, request, requestOptions));
    }

    private async __forecasts(
        portfolioId: string,
        request: Earth.PortfoliosForecastsRequest,
        requestOptions?: Portfolios.RequestOptions,
    ): Promise<core.WithRawResponse<Earth.TimeSeriesFeatureCollectionModel>> {
        const { id, variables, init_time: initTime } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (id != null) {
            if (Array.isArray(id)) {
                _queryParams.id = id.map((item) => item);
            } else {
                _queryParams.id = id;
            }
        }

        if (variables != null) {
            if (Array.isArray(variables)) {
                _queryParams.variables = variables.map((item) => item);
            } else {
                _queryParams.variables = variables;
            }
        }

        _queryParams.init_time = initTime;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.EarthEnvironment.Production,
                `portfolios/${core.url.encodePathParam(portfolioId)}/forecasts`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as Earth.TimeSeriesFeatureCollectionModel,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Earth.UnprocessableEntityError(
                        _response.error.body as Earth.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.EarthError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.EarthError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.EarthTimeoutError(
                    "Timeout exceeded when calling GET /portfolios/{portfolio_id}/forecasts.",
                );
            case "unknown":
                throw new errors.EarthError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Return a GeoJSON FeatureCollection of observations for a portfolio.
     *
     * @param {string} portfolioId
     * @param {Earth.PortfoliosObservationsRequest} request
     * @param {Portfolios.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Earth.UnprocessableEntityError}
     *
     * @example
     *     await client.portfolios.observations("portfolio_id", {
     *         valid_time_start: "2024-01-15T09:30:00Z",
     *         valid_time_end: "2024-01-15T09:30:00Z"
     *     })
     */
    public observations(
        portfolioId: string,
        request: Earth.PortfoliosObservationsRequest,
        requestOptions?: Portfolios.RequestOptions,
    ): core.HttpResponsePromise<Earth.TimeSeriesFeatureCollectionModel> {
        return core.HttpResponsePromise.fromPromise(this.__observations(portfolioId, request, requestOptions));
    }

    private async __observations(
        portfolioId: string,
        request: Earth.PortfoliosObservationsRequest,
        requestOptions?: Portfolios.RequestOptions,
    ): Promise<core.WithRawResponse<Earth.TimeSeriesFeatureCollectionModel>> {
        const { id, variables, valid_time_start: validTimeStart, valid_time_end: validTimeEnd } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (id != null) {
            if (Array.isArray(id)) {
                _queryParams.id = id.map((item) => item);
            } else {
                _queryParams.id = id;
            }
        }

        if (variables != null) {
            if (Array.isArray(variables)) {
                _queryParams.variables = variables.map((item) => item);
            } else {
                _queryParams.variables = variables;
            }
        }

        _queryParams.valid_time_start = validTimeStart;
        _queryParams.valid_time_end = validTimeEnd;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.EarthEnvironment.Production,
                `portfolios/${core.url.encodePathParam(portfolioId)}/observations`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as Earth.TimeSeriesFeatureCollectionModel,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Earth.UnprocessableEntityError(
                        _response.error.body as Earth.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.EarthError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.EarthError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.EarthTimeoutError(
                    "Timeout exceeded when calling GET /portfolios/{portfolio_id}/observations.",
                );
            case "unknown":
                throw new errors.EarthError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Return the latest initialization time for a portfolio.
     *
     * @param {string} portfolioId
     * @param {Earth.PortfoliosInitTimeRequest} request
     * @param {Portfolios.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Earth.UnprocessableEntityError}
     *
     * @example
     *     await client.portfolios.initTime("portfolio_id", {
     *         time: "2024-01-15T09:30:00Z"
     *     })
     */
    public initTime(
        portfolioId: string,
        request: Earth.PortfoliosInitTimeRequest,
        requestOptions?: Portfolios.RequestOptions,
    ): core.HttpResponsePromise<string> {
        return core.HttpResponsePromise.fromPromise(this.__initTime(portfolioId, request, requestOptions));
    }

    private async __initTime(
        portfolioId: string,
        request: Earth.PortfoliosInitTimeRequest,
        requestOptions?: Portfolios.RequestOptions,
    ): Promise<core.WithRawResponse<string>> {
        const { time } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams.time = time;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.EarthEnvironment.Production,
                `portfolios/${core.url.encodePathParam(portfolioId)}/init_time`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as string, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Earth.UnprocessableEntityError(
                        _response.error.body as Earth.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.EarthError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.EarthError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.EarthTimeoutError(
                    "Timeout exceeded when calling GET /portfolios/{portfolio_id}/init_time.",
                );
            case "unknown":
                throw new errors.EarthError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders(): Promise<Record<string, string | undefined>> {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { "X-API-KEY": apiKeyValue };
    }
}
