// This file was auto-generated by Fern from our API Definition.

import * as Earth from "../../../../src/api/index";
import { EarthClient } from "../../../../src/Client";
import { mockServerPool } from "../../../mock-server/MockServerPool";

describe("Forecast", () => {
    test("daily (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new EarthClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            latitude: 1.1,
            longitude: 1.1,
            forecast_time: "2024-01-15T09:30:00Z",
            timezone: "America/Los_Angeles",
            utc_offset: -28800,
            elevation: 1,
            units: {
                elevation: "elevation",
                temperature: "temperature",
                feels_like_temperature: "feels_like_temperature",
                precipitation_accumulation: "precipitation_accumulation",
                precipitation_probability: "precipitation_probability",
                snowfall_accumulation: "snowfall_accumulation",
                cloud_cover: "cloud_cover",
                humidity: "humidity",
                wind_speed: "wind_speed",
                wind_direction: "wind_direction",
                dewpoint_temperature: "dewpoint_temperature",
                pressure: "pressure",
                downward_solar_radiation: "downward_solar_radiation",
                wind_speed_100m: "wind_speed_100m",
                wind_direction_100m: "wind_direction_100m",
                global_horizontal_irradiation: "global_horizontal_irradiation",
                direct_normal_irradiation: "direct_normal_irradiation",
                diffuse_horizontal_irradiation: "diffuse_horizontal_irradiation",
            },
            daily: [
                {
                    timestamp: "timestamp",
                    temperature: 1.1,
                    precipitation_accumulation: 1.1,
                    precipitation_probability: 1,
                    precipitation_type: "liquid",
                    snowfall_accumulation: 1.1,
                    cloud_cover: 1,
                    humidity: 1,
                    wind_speed: 1.1,
                    wind_direction: 1.1,
                    dewpoint_temperature: 1.1,
                    pressure: 1.1,
                    downward_solar_radiation: 1.1,
                    wind_speed_100m: 1.1,
                    wind_direction_100m: 1.1,
                    feels_like_temperature: 1.1,
                    weather_code: "clear-night",
                    global_horizontal_irradiation: 1.1,
                    direct_normal_irradiation: 1.1,
                    diffuse_horizontal_irradiation: 1.1,
                    max_temperature: 1.1,
                    min_temperature: 1.1,
                },
            ],
        };
        server
            .mockEndpoint()
            .get("/past/forecast/daily")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.weather.past.forecast.daily({
            latitude: 47.6061,
            longitude: -122.3328,
            time: "2024-01-01T00:00:00Z",
            timezone: "local",
            units: "metric",
        });
        expect(response).toEqual({
            latitude: 1.1,
            longitude: 1.1,
            forecast_time: "2024-01-15T09:30:00Z",
            timezone: "America/Los_Angeles",
            utc_offset: -28800,
            elevation: 1,
            units: {
                elevation: "elevation",
                temperature: "temperature",
                feels_like_temperature: "feels_like_temperature",
                precipitation_accumulation: "precipitation_accumulation",
                precipitation_probability: "precipitation_probability",
                snowfall_accumulation: "snowfall_accumulation",
                cloud_cover: "cloud_cover",
                humidity: "humidity",
                wind_speed: "wind_speed",
                wind_direction: "wind_direction",
                dewpoint_temperature: "dewpoint_temperature",
                pressure: "pressure",
                downward_solar_radiation: "downward_solar_radiation",
                wind_speed_100m: "wind_speed_100m",
                wind_direction_100m: "wind_direction_100m",
                global_horizontal_irradiation: "global_horizontal_irradiation",
                direct_normal_irradiation: "direct_normal_irradiation",
                diffuse_horizontal_irradiation: "diffuse_horizontal_irradiation",
            },
            daily: [
                {
                    timestamp: "timestamp",
                    temperature: 1.1,
                    precipitation_accumulation: 1.1,
                    precipitation_probability: 1,
                    precipitation_type: "liquid",
                    snowfall_accumulation: 1.1,
                    cloud_cover: 1,
                    humidity: 1,
                    wind_speed: 1.1,
                    wind_direction: 1.1,
                    dewpoint_temperature: 1.1,
                    pressure: 1.1,
                    downward_solar_radiation: 1.1,
                    wind_speed_100m: 1.1,
                    wind_direction_100m: 1.1,
                    feels_like_temperature: 1.1,
                    weather_code: "clear-night",
                    global_horizontal_irradiation: 1.1,
                    direct_normal_irradiation: 1.1,
                    diffuse_horizontal_irradiation: 1.1,
                    max_temperature: 1.1,
                    min_temperature: 1.1,
                },
            ],
        });
    });

    test("daily (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new EarthClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .get("/past/forecast/daily")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.weather.past.forecast.daily({
                latitude: 1.1,
                longitude: 1.1,
                time: "2024-01-15T09:30:00Z",
            });
        }).rejects.toThrow(Earth.UnprocessableEntityError);
    });

    test("hourly (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new EarthClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            latitude: 1.1,
            longitude: 1.1,
            forecast_time: "2024-01-15T09:30:00Z",
            timezone: "America/Los_Angeles",
            utc_offset: -28800,
            elevation: 1,
            units: {
                elevation: "elevation",
                temperature: "temperature",
                feels_like_temperature: "feels_like_temperature",
                precipitation_accumulation: "precipitation_accumulation",
                precipitation_probability: "precipitation_probability",
                snowfall_accumulation: "snowfall_accumulation",
                cloud_cover: "cloud_cover",
                humidity: "humidity",
                wind_speed: "wind_speed",
                wind_direction: "wind_direction",
                dewpoint_temperature: "dewpoint_temperature",
                pressure: "pressure",
                downward_solar_radiation: "downward_solar_radiation",
                wind_speed_100m: "wind_speed_100m",
                wind_direction_100m: "wind_direction_100m",
                global_horizontal_irradiation: "global_horizontal_irradiation",
                direct_normal_irradiation: "direct_normal_irradiation",
                diffuse_horizontal_irradiation: "diffuse_horizontal_irradiation",
            },
            hourly: [
                {
                    timestamp: "2024-01-15T09:30:00Z",
                    temperature: 1.1,
                    precipitation_accumulation: 1.1,
                    precipitation_probability: 1,
                    precipitation_type: "liquid",
                    snowfall_accumulation: 1.1,
                    cloud_cover: 1,
                    humidity: 1,
                    wind_speed: 1.1,
                    wind_direction: 1.1,
                    dewpoint_temperature: 1.1,
                    pressure: 1.1,
                    downward_solar_radiation: 1.1,
                    wind_speed_100m: 1.1,
                    wind_direction_100m: 1.1,
                    feels_like_temperature: 1.1,
                    weather_code: "clear-night",
                    global_horizontal_irradiation: 1.1,
                    direct_normal_irradiation: 1.1,
                    diffuse_horizontal_irradiation: 1.1,
                },
            ],
        };
        server
            .mockEndpoint()
            .get("/past/forecast/hourly")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.weather.past.forecast.hourly({
            latitude: 47.6061,
            longitude: -122.3328,
            time: "2024-01-01T00:00:00Z",
            timezone: "local",
            units: "metric",
        });
        expect(response).toEqual({
            latitude: 1.1,
            longitude: 1.1,
            forecast_time: "2024-01-15T09:30:00Z",
            timezone: "America/Los_Angeles",
            utc_offset: -28800,
            elevation: 1,
            units: {
                elevation: "elevation",
                temperature: "temperature",
                feels_like_temperature: "feels_like_temperature",
                precipitation_accumulation: "precipitation_accumulation",
                precipitation_probability: "precipitation_probability",
                snowfall_accumulation: "snowfall_accumulation",
                cloud_cover: "cloud_cover",
                humidity: "humidity",
                wind_speed: "wind_speed",
                wind_direction: "wind_direction",
                dewpoint_temperature: "dewpoint_temperature",
                pressure: "pressure",
                downward_solar_radiation: "downward_solar_radiation",
                wind_speed_100m: "wind_speed_100m",
                wind_direction_100m: "wind_direction_100m",
                global_horizontal_irradiation: "global_horizontal_irradiation",
                direct_normal_irradiation: "direct_normal_irradiation",
                diffuse_horizontal_irradiation: "diffuse_horizontal_irradiation",
            },
            hourly: [
                {
                    timestamp: "2024-01-15T09:30:00Z",
                    temperature: 1.1,
                    precipitation_accumulation: 1.1,
                    precipitation_probability: 1,
                    precipitation_type: "liquid",
                    snowfall_accumulation: 1.1,
                    cloud_cover: 1,
                    humidity: 1,
                    wind_speed: 1.1,
                    wind_direction: 1.1,
                    dewpoint_temperature: 1.1,
                    pressure: 1.1,
                    downward_solar_radiation: 1.1,
                    wind_speed_100m: 1.1,
                    wind_direction_100m: 1.1,
                    feels_like_temperature: 1.1,
                    weather_code: "clear-night",
                    global_horizontal_irradiation: 1.1,
                    direct_normal_irradiation: 1.1,
                    diffuse_horizontal_irradiation: 1.1,
                },
            ],
        });
    });

    test("hourly (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new EarthClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .get("/past/forecast/hourly")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.weather.past.forecast.hourly({
                latitude: 1.1,
                longitude: 1.1,
                time: "2024-01-15T09:30:00Z",
            });
        }).rejects.toThrow(Earth.UnprocessableEntityError);
    });
});
