/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Earth from "../../../../../../../../index";

/**
 * @example
 *     {
 *         latitude: 47.6061,
 *         longitude: -122.3328
 *     }
 */
export interface RegionalUsaRequest {
    latitude: number;
    longitude: number;
    timezone?: Earth.Timezone;
    units?: Earth.Units;
}
