// This file was auto-generated by Fern from our API Definition.

/**
 * One forecast-issued alarm under one alert threshold — the precision (cry-wolf) side.
 *
 * The complement to `EventOutcome`: every alert the forecast would have raised,
 * whether or not it matched a real episode. Returned for the whole period so FAR /
 * reissue burden can be computed across bins and thresholds client-side.
 */
export interface AlarmOutcome {
    segment: string;
    alarm_id: number;
    bin: string;
    threshold: number;
    alarm_start: string;
    alarm_end: string;
    issued_lead_h?: number | undefined;
    max_prob?: number | undefined;
    n_reissues: number;
    matched: boolean;
    matched_severity?: number | undefined;
    false_alarm: boolean;
}
