// This file was auto-generated by Fern from our API Definition.

import type * as Earth from "../index.js";

export interface CycloneForecastResponse {
    storm_id: string;
    storm_name: string;
    type?: string;
    category: number;
    position: Earth.GeoLocation;
    forecast_time: string;
    forecast_source_info: string;
    forecast_last_updated: string;
}
