/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Earth from "../index";

export interface CycloneForecastResponse {
    storm_id: string;
    storm_name: string;
    type: string;
    category: number;
    position: Earth.GeoLocation;
    forecast_time: string;
    forecast_source_info: string;
    last_updated: string;
}
