/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface DailyConditions {
    timestamp: string;
    temperature?: number;
    dewpoint_temperature?: number;
    precipitation_accumulation?: number;
    wind_speed?: number;
    wind_direction?: number;
    pressure?: number;
    downward_solar_radiation?: number;
    wind_speed_100m?: number;
    wind_direction_100m?: number;
    max_temperature?: number;
    min_temperature?: number;
}
