/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Silurian from "../index";

export interface DailyWeatherResponse {
    latitude: number;
    longitude: number;
    timezone: string;
    utc_offset: number;
    elevation?: number;
    units: Silurian.Units;
    daily: Silurian.DailyConditions[];
}
