/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Earth from "../index";

export interface DailyWeatherResponse {
    latitude: number;
    longitude: number;
    timezone: string;
    utc_offset: number;
    elevation?: number;
    units: DailyWeatherResponse.Units;
    daily: Earth.DailyConditions[];
}

export namespace DailyWeatherResponse {
    export type Units = Earth.MetricUnits | Earth.ImperialUnits;
}
