// This file was auto-generated by Fern from our API Definition.

import type * as Earth from "../index.js";

export interface DailyConditions {
    timestamp: string;
    temperature?: number | undefined;
    precipitation_accumulation?: number | undefined;
    precipitation_probability?: number | undefined;
    precipitation_type?: Earth.PrecipitationType | undefined;
    snowfall_accumulation?: number | undefined;
    cloud_cover?: number | undefined;
    humidity?: number | undefined;
    wind_speed?: number | undefined;
    wind_direction?: number | undefined;
    dewpoint_temperature?: number | undefined;
    pressure?: number | undefined;
    downward_solar_radiation?: number | undefined;
    wind_speed_100m?: number | undefined;
    wind_direction_100m?: number | undefined;
    feels_like_temperature?: number | undefined;
    weather_code?: Earth.WeatherCode | undefined;
    global_horizontal_irradiation?: number | undefined;
    direct_normal_irradiation?: number | undefined;
    diffuse_horizontal_irradiation?: number | undefined;
    max_temperature?: number | undefined;
    min_temperature?: number | undefined;
}
