// This file was auto-generated by Fern from our API Definition.

/**
 * Detection rate (POD) for one (forecast day, severity, alert-threshold) cell.
 */
export interface DetectionPoint {
    lead_day: number;
    severity: number;
    prob: number;
    n_events: number;
    hits: number;
    pod: number;
}
