// This file was auto-generated by Fern from our API Definition.

/**
 * One observed event episode under one alert threshold — the recall (catch) side.
 *
 * Rows for the whole period (all bins, both thresholds) are returned so the UI can
 * build the cross-aggregation operating-point view client-side; `warning_lead_h` is
 * referenced to onset (null ⇒ the episode was never flagged at this threshold).
 */
export interface EventOutcome {
    segment: string;
    episode_id: number;
    episode_start: string;
    episode_end: string;
    total_severity: number;
    peak_window_severity: number;
    bin: string;
    threshold: number;
    warning_lead_h?: number | undefined;
    n_crossings: number;
}
