// This file was auto-generated by Fern from our API Definition.

import type * as Earth from "../index.js";

/**
 * Feature Model
 */
export interface Feature {
    bbox?: unknown[] | undefined;
    type: "Feature";
    geometry?: Earth.FeatureGeometry | undefined;
    properties?: Feature.Properties | undefined;
    id?: Feature.Id | undefined;
}

export namespace Feature {
    export type Properties = Record<string, unknown> | Earth.BaseModel;
    export type Id = number | string;
}
