// This file was auto-generated by Fern from our API Definition.

import type * as Earth from "../index.js";

/**
 * FeatureCollection Model
 */
export interface FeatureCollection {
    bbox?: unknown[];
    type: "FeatureCollection";
    features: Earth.Feature[];
}
