/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Earth from "../index";

/**
 * FeatureCollection Model
 */
export interface FeatureCollection {
    bbox?: unknown[];
    type: "FeatureCollection";
    features: Earth.Feature[];
}
