// This file was auto-generated by Fern from our API Definition.

import type * as Earth from "../index.js";

/**
 * Feature Model
 */
export interface Feature {
    bbox?: unknown[];
    type: "Feature";
    geometry?: Earth.FeatureGeometry;
    properties?: Feature.Properties;
    id?: Feature.Id;
}

export namespace Feature {
    export type Properties = Record<string, unknown> | Earth.BaseModel;
    export type Id = number | string;
}
