/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Earth from "../index";

export interface ForecastTable {
    schema_version?: string;
    units?: Record<string, string | undefined>;
    data: Earth.ForecastRow[];
}
