/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ForecastRow {
    /** UTC valid‑time of the forecast */
    timestamp: string;
    /** Asset name */
    asset_name: string;
    /** Asset id */
    asset_id: number;
    latitude: number;
    longitude: number;
    variable: string;
    value: number;
}
