// This file was auto-generated by Fern from our API Definition.

import type * as Earth from "../index.js";

/**
 * GeometryCollection Model
 */
export interface GeometryCollection {
    bbox?: unknown[];
    geometries: Earth.GeometryCollectionGeometriesItem[];
}
