/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Earth from "../index";

/**
 * GeometryCollection Model
 */
export interface GeometryCollection {
    bbox?: unknown[];
    geometries: Earth.GeometryCollectionGeometriesItem[];
}
