/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Earth from "../index";

export type GeometryCollectionGeometriesItem =
    | Earth.GeometryCollectionGeometriesItem.GeometryCollection
    | Earth.GeometryCollectionGeometriesItem.LineString
    | Earth.GeometryCollectionGeometriesItem.MultiLineString
    | Earth.GeometryCollectionGeometriesItem.MultiPoint
    | Earth.GeometryCollectionGeometriesItem.MultiPolygon
    | Earth.GeometryCollectionGeometriesItem.Point
    | Earth.GeometryCollectionGeometriesItem.Polygon;

export namespace GeometryCollectionGeometriesItem {
    export interface GeometryCollection extends Earth.GeometryCollection {
        type: "GeometryCollection";
    }

    export interface LineString extends Earth.LineString {
        type: "LineString";
    }

    export interface MultiLineString extends Earth.MultiLineString {
        type: "MultiLineString";
    }

    export interface MultiPoint extends Earth.MultiPoint {
        type: "MultiPoint";
    }

    export interface MultiPolygon extends Earth.MultiPolygon {
        type: "MultiPolygon";
    }

    export interface Point extends Earth.Point {
        type: "Point";
    }

    export interface Polygon extends Earth.Polygon {
        type: "Polygon";
    }
}
