// This file was auto-generated by Fern from our API Definition.

import type * as Earth from "../index.js";

export interface GftusHourlyWeatherResponse {
    latitude: number;
    longitude: number;
    forecast_time: string;
    timezone: string;
    utc_offset: number;
    elevation?: number | undefined;
    units: Earth.GftusBaseUnits;
    hourly: Earth.GftusHourlyConditions[];
}
