// This file was auto-generated by Fern from our API Definition.

export interface GftusBaseUnits {
    elevation: string;
    temperature: string;
    humidity?: string | undefined;
    wind_speed: string;
    wind_direction?: string | undefined;
    wind_speed_80m: string;
    wind_direction_80m?: string | undefined;
    dewpoint_temperature: string;
    feels_like_temperature: string;
    pressure: string;
    downward_solar_radiation: string;
    precipitation_accumulation: string;
    precipitation_probability?: string | undefined;
    cloud_cover?: string | undefined;
}
