/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GftusBaseUnits {
    elevation: string;
    temperature: string;
    humidity?: string;
    wind_speed: string;
    wind_direction?: string;
    wind_speed_80m: string;
    wind_direction_80m?: string;
    dewpoint_temperature: string;
    feels_like_temperature: string;
    pressure: string;
    downward_solar_radiation: string;
    precipitation_accumulation: string;
    precipitation_probability?: string;
    cloud_cover?: string;
}
