// This file was auto-generated by Fern from our API Definition.

export interface GftusHourlyConditions {
    timestamp: string;
    temperature?: number | undefined;
    humidity?: number | undefined;
    wind_speed?: number | undefined;
    wind_gust?: number | undefined;
    wind_direction?: number | undefined;
    wind_speed_80m?: number | undefined;
    wind_direction_80m?: number | undefined;
    dewpoint_temperature?: number | undefined;
    feels_like_temperature?: number | undefined;
    pressure?: number | undefined;
    precipitation_accumulation?: number | undefined;
    precipitation_probability?: number | undefined;
    cloud_cover?: number | undefined;
    downward_solar_radiation?: number | undefined;
}
