// This file was auto-generated by Fern from our API Definition.

import type * as Earth from "../index.js";

export interface Histogram {
    buckets: Earth.Bucket[];
    count: number;
    sum: number;
}
