/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Earth from "../index";

export interface HourlyWeatherResponse {
    latitude: number;
    longitude: number;
    forecast_time: string;
    timezone: string;
    utc_offset: number;
    elevation?: number;
    units: HourlyWeatherResponse.Units;
    hourly: Earth.HourlyConditions[];
}

export namespace HourlyWeatherResponse {
    export type Units = Earth.MetricUnits | Earth.ImperialUnits;
}
