/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ImperialUnits {
    elevation?: string;
    temperature?: string;
    feels_like_temperature?: string;
    precipitation_accumulation?: string;
    precipitation_probability?: string;
    snowfall_accumulation?: string;
    cloud_cover?: string;
    humidity?: string;
    wind_speed?: string;
    wind_direction?: string;
    dewpoint_temperature?: string;
    pressure?: string;
    downward_solar_radiation?: string;
    wind_speed_100m?: string;
    wind_direction_100m?: string;
    global_horizontal_irradiation?: string;
    direct_normal_irradiation?: string;
    diffuse_horizontal_irradiation?: string;
}
