/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ImperialUnits {
    elevation?: string;
    temperature?: string;
    dewpoint_temperature?: string;
    precipitation_accumulation?: string;
    snowfall?: string;
    wind_speed?: string;
    wind_speed_100m?: string;
    pressure?: string;
    downward_solar_radiation?: string;
}
