// This file was auto-generated by Fern from our API Definition.

export interface ImperialUnits {
    elevation?: string | undefined;
    temperature?: string | undefined;
    feels_like_temperature?: string | undefined;
    precipitation_accumulation?: string | undefined;
    precipitation_probability?: string | undefined;
    snowfall_accumulation?: string | undefined;
    cloud_cover?: string | undefined;
    humidity?: string | undefined;
    wind_speed?: string | undefined;
    wind_direction?: string | undefined;
    dewpoint_temperature?: string | undefined;
    pressure?: string | undefined;
    downward_solar_radiation?: string | undefined;
    wind_speed_100m?: string | undefined;
    wind_direction_100m?: string | undefined;
    global_horizontal_irradiation?: string | undefined;
    direct_normal_irradiation?: string | undefined;
    diffuse_horizontal_irradiation?: string | undefined;
}
