// This file was auto-generated by Fern from our API Definition.

import type * as Earth from "../index.js";

/**
 * LineString Model
 */
export interface LineString {
    bbox?: unknown[];
    coordinates: LineString.Coordinates.Item[];
}

export namespace LineString {
    export type Coordinates = Coordinates.Item[];

    export namespace Coordinates {
        export type Item = Earth.Position2D | Earth.Position3D;
    }
}
