/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Earth from "../index";

/**
 * MultiPolygon Model
 */
export interface MultiPolygon {
    bbox?: unknown[];
    coordinates: MultiPolygon.Coordinates.Item[][][];
}

export namespace MultiPolygon {
    export type Coordinates = Coordinates.Item[];

    export namespace Coordinates {
        export type Item = Earth.Position2D | Earth.Position3D;
    }
}
