/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Earth from "../index";

/**
 * MultiLineString Model
 */
export interface MultiLineString {
    bbox?: unknown[];
    coordinates: MultiLineString.Coordinates.Item[][];
}

export namespace MultiLineString {
    export type Coordinates = Coordinates.Item[];

    export namespace Coordinates {
        export type Item = Earth.Position2D | Earth.Position3D;
    }
}
