/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Earth from "../index";

/**
 * Polygon Model
 */
export interface Polygon {
    bbox?: unknown[];
    coordinates: Polygon.Coordinates.Item[][];
}

export namespace Polygon {
    export type Coordinates = Coordinates.Item[];

    export namespace Coordinates {
        export type Item = Earth.Position2D | Earth.Position3D;
    }
}
