/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PrecipitationType = "liquid" | "snow" | "hail" | "sleet" | "freezing_rain";
export const PrecipitationType = {
    Liquid: "liquid",
    Snow: "snow",
    Hail: "hail",
    Sleet: "sleet",
    FreezingRain: "freezing_rain",
} as const;
