// This file was auto-generated by Fern from our API Definition.

export const PrecipitationType = {
    Liquid: "liquid",
    Snow: "snow",
    Hail: "hail",
    Sleet: "sleet",
    FreezingRain: "freezing_rain",
} as const;
export type PrecipitationType = (typeof PrecipitationType)[keyof typeof PrecipitationType];
