// This file was auto-generated by Fern from our API Definition.

/**
 * One reliability-diagram bin: predicted probability vs observed frequency.
 */
export interface ReliabilityPoint {
    forecast: number;
    observed: number;
    count: number;
}
