// This file was auto-generated by Fern from our API Definition.

import type * as Earth from "../index.js";

/**
 * Aggregate forecast-skill scorecard for a portfolio at one (period, bin) slice.
 */
export interface ScorecardModel {
    portfolio_id: string;
    period: string;
    bin: string;
    model_version?: string | undefined;
    computed_at?: string | undefined;
    kpi: Earth.SkillKpis;
    skill_by_lead: Earth.SkillByLeadPoint[];
    reliability: Earth.ReliabilityPoint[];
    detection: Earth.DetectionPoint[];
    events?: Earth.EventOutcome[] | undefined;
    alarms?: Earth.AlarmOutcome[] | undefined;
}
