// This file was auto-generated by Fern from our API Definition.

/**
 * POD / FAR / Brier at a single forecast lead time.
 */
export interface SkillByLeadPoint {
    lead_h: number;
    pod: number;
    far: number;
    brier: number;
}
