// This file was auto-generated by Fern from our API Definition.

/**
 * Headline verification KPIs for one (period, bin) slice.
 */
export interface SkillKpis {
    pod: number;
    far: number;
    f1: number;
    pr_auc: number;
    brier: number;
    brier_delta?: number | undefined;
    median_lead_h?: number | undefined;
    days_scored: number;
}
