// This file was auto-generated by Fern from our API Definition.

import type * as Earth from "../index.js";

export interface Summary {
    quantiles: Earth.Quantile[];
    count: number;
    sum: number;
}
