// This file was auto-generated by Fern from our API Definition.

import type * as Earth from "../index.js";

/**
 * GeoJSON Feature with time-series properties.
 */
export interface TimeSeriesFeatureModel {
    bbox?: unknown[] | undefined;
    type: "Feature";
    geometry?: Earth.TimeSeriesFeatureModelGeometry | undefined;
    properties?: Earth.TimeSeriesPropertiesModel | undefined;
    id?: TimeSeriesFeatureModel.Id | undefined;
}

export namespace TimeSeriesFeatureModel {
    export type Id = number | string;
}
