// This file was auto-generated by Fern from our API Definition.

import type * as Earth from "../index.js";

/**
 * GeoJSON FeatureCollection for time-series features.
 */
export interface TimeSeriesFeatureCollectionModel {
    bbox?: unknown[];
    type: "FeatureCollection";
    features: Earth.TimeSeriesFeatureModel[];
}
