// This file was auto-generated by Fern from our API Definition.

import type * as Earth from "../index.js";

/**
 * Concrete model for OpenAPI schema generation.
 */
export interface TimeSeriesPropertiesModel {
    datetimes: string[];
    static: TimeSeriesPropertiesModel.Static;
    /** Accepts any additional properties */
    [key: string]: any;
}

export namespace TimeSeriesPropertiesModel {
    export type Static = Record<string, unknown> | Earth.BaseModel;
}
