/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An enumeration.
 */
export type Timezone = "local" | "utc";
export const Timezone = {
    Local: "local",
    Utc: "utc",
} as const;
