// This file was auto-generated by Fern from our API Definition.

import type * as Earth from "../index.js";

/**
 * GeoJSON Feature with time-series properties.
 */
export interface TimeSeriesFeatureModel {
    bbox?: unknown[];
    type: "Feature";
    geometry?: Earth.TimeSeriesFeatureModelGeometry;
    properties?: Earth.TimeSeriesPropertiesModel;
    id?: TimeSeriesFeatureModel.Id;
}

export namespace TimeSeriesFeatureModel {
    export type Id = number | string;
}
