// This file was auto-generated by Fern from our API Definition.

import type * as Earth from "../index.js";

export type TimeSeriesFeatureModelGeometry =
    | Earth.TimeSeriesFeatureModelGeometry.GeometryCollection
    | Earth.TimeSeriesFeatureModelGeometry.LineString
    | Earth.TimeSeriesFeatureModelGeometry.MultiLineString
    | Earth.TimeSeriesFeatureModelGeometry.MultiPoint
    | Earth.TimeSeriesFeatureModelGeometry.MultiPolygon
    | Earth.TimeSeriesFeatureModelGeometry.Point
    | Earth.TimeSeriesFeatureModelGeometry.Polygon;

export namespace TimeSeriesFeatureModelGeometry {
    export interface GeometryCollection extends Earth.GeometryCollection {
        type: "GeometryCollection";
    }

    export interface LineString extends Earth.LineString {
        type: "LineString";
    }

    export interface MultiLineString extends Earth.MultiLineString {
        type: "MultiLineString";
    }

    export interface MultiPoint extends Earth.MultiPoint {
        type: "MultiPoint";
    }

    export interface MultiPolygon extends Earth.MultiPolygon {
        type: "MultiPolygon";
    }

    export interface Point extends Earth.Point {
        type: "Point";
    }

    export interface Polygon extends Earth.Polygon {
        type: "Polygon";
    }
}
