// This file was auto-generated by Fern from our API Definition.

export const Timezone = {
    Local: "local",
    Utc: "utc",
} as const;
export type Timezone = (typeof Timezone)[keyof typeof Timezone];
