/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An enumeration.
 */
export type Units = "metric" | "imperial";
export const Units = {
    Metric: "metric",
    Imperial: "imperial",
} as const;
