/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type Units = "metric" | "imperial";
export const Units = {
    Metric: "metric",
    Imperial: "imperial",
} as const;
