// This file was auto-generated by Fern from our API Definition.

export const Units = {
    Metric: "metric",
    Imperial: "imperial",
} as const;
export type Units = (typeof Units)[keyof typeof Units];
