// This file was auto-generated by Fern from our API Definition.

import type * as Earth from "../index.js";

/**
 * VectorMetric is modelled on the Vector observability pipeline event schema:
 * https://vector.dev/docs/about/under-the-hood/architecture/data-model/metric/
 *
 * Each metric carries a name, a tag map, a timestamp, a sampling interval, and
 * exactly one value payload (counter, gauge, set, distribution, histogram, or
 * summary).  Each metric may also have attributes, though these should be limited
 * in cardinality as each attribute combination logically creates an independent
 * metric series.
 *
 * The implementation here also allows for batched metric values of the same name,
 * kind, and value payload for efficiency.
 */
export interface VectorMetric {
    namespace?: string | undefined;
    name: string;
    tags: Record<string, string>;
    kind: VectorMetric.Kind;
    timestamp: VectorMetric.Timestamp;
    interval_ms: VectorMetric.IntervalMs;
    counter?: VectorMetric.Counter | undefined;
    gauge?: VectorMetric.Gauge | undefined;
    set?: VectorMetric.Set | undefined;
    distribution?: VectorMetric.Distribution | undefined;
    histogram?: VectorMetric.Histogram | undefined;
    summary?: VectorMetric.Summary | undefined;
}

export namespace VectorMetric {
    export const Kind = {
        Absolute: "absolute",
        Incremental: "incremental",
    } as const;
    export type Kind = (typeof Kind)[keyof typeof Kind];
    export type Timestamp = string | string[];
    export type IntervalMs = number | number[];
    export type Counter = number | number[];
    export type Gauge = number | number[];
    export type Set = string[] | string[][];
    export type Distribution = Earth.Distribution | Earth.Distribution[];
    export type Histogram = Earth.Histogram | Earth.Histogram[];
    export type Summary = Earth.Summary | Earth.Summary[];
}
