// This file was auto-generated by Fern from our API Definition.

export const WeatherCode = {
    ClearNight: "clear-night",
    ClearDay: "clear-day",
    PartlyCloudyDay: "partly-cloudy-day",
    PartlyCloudyNight: "partly-cloudy-night",
    Cloudy: "cloudy",
    Rain: "rain",
    Snow: "snow",
} as const;
export type WeatherCode = (typeof WeatherCode)[keyof typeof WeatherCode];
