/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type WeatherCode =
    | "clear-night"
    | "clear-day"
    | "partly-cloudy-day"
    | "partly-cloudy-night"
    | "cloudy"
    | "rain"
    | "snow";
export const WeatherCode = {
    ClearNight: "clear-night",
    ClearDay: "clear-day",
    PartlyCloudyDay: "partly-cloudy-day",
    PartlyCloudyNight: "partly-cloudy-night",
    Cloudy: "cloudy",
    Rain: "rain",
    Snow: "snow",
} as const;
