/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Silurian from "../../../../index";

/**
 * @example
 *     {
 *         latitude: 1.1,
 *         longitude: 1.1
 *     }
 */
export interface ForecastsCreateHourlyRequest {
    latitude: number;
    longitude: number;
    timezone?: Silurian.Timezone;
    units?: Silurian.Units;
}
