// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../../../../../core/headers.js";
import * as core from "../../../../../../../../core/index.js";
import * as environments from "../../../../../../../../environments.js";
import * as errors from "../../../../../../../../errors/index.js";
import * as Earth from "../../../../../../../index.js";

export declare namespace Regional {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class Regional {
    protected readonly _options: Regional.Options;

    constructor(_options: Regional.Options = {}) {
        this._options = _options;
    }

    /**
     * Get hourly weather forecast for a specific location and time
     *
     * @param {Earth.weather.experimental.RegionalUsaRequest} request
     * @param {Regional.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Earth.UnprocessableEntityError}
     *
     * @example
     *     await client.weather.experimental.regional.usa({
     *         latitude: 47.6061,
     *         longitude: -122.3328,
     *         timezone: "local",
     *         units: "metric"
     *     })
     */
    public usa(
        request: Earth.weather.experimental.RegionalUsaRequest,
        requestOptions?: Regional.RequestOptions,
    ): core.HttpResponsePromise<Earth.GftusHourlyWeatherResponse> {
        return core.HttpResponsePromise.fromPromise(this.__usa(request, requestOptions));
    }

    private async __usa(
        request: Earth.weather.experimental.RegionalUsaRequest,
        requestOptions?: Regional.RequestOptions,
    ): Promise<core.WithRawResponse<Earth.GftusHourlyWeatherResponse>> {
        const { latitude, longitude, timezone, units } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams.latitude = latitude.toString();
        _queryParams.longitude = longitude.toString();
        if (timezone != null) {
            _queryParams.timezone = timezone;
        }

        if (units != null) {
            _queryParams.units = units;
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.EarthEnvironment.Production,
                "experimental/regional/usa",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Earth.GftusHourlyWeatherResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Earth.UnprocessableEntityError(
                        _response.error.body as Earth.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.EarthError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.EarthError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.EarthTimeoutError("Timeout exceeded when calling GET /experimental/regional/usa.");
            case "unknown":
                throw new errors.EarthError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders(): Promise<Record<string, string | undefined>> {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { "X-API-KEY": apiKeyValue };
    }
}
