/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Earth from "../../../../index";

/**
 * @example
 *     {}
 */
export interface GetForecastTrackCycloneForecastsStormIdTrackGetRequest {
    /**
     * *Default value: (current time) - Default time zone: UTC*
     */
    time?: string;
    /**
     * *Value must be > P0D*
     */
    max_lead_time?: string;
    model?: Earth.ModelName;
}
