/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Earth from "../../../../index";

/**
 * @example
 *     {}
 */
export interface QueryForecastsCycloneForecastsGetRequest {
    /**
     * *Default value: (current time) - Default time zone: UTC*
     */
    time?: string;
    min_storm_category?: number;
    model?: Earth.ModelName;
}
