// This file was auto-generated by Fern from our API Definition.

export const ForecastsConeRequestModel = {
    Ofcl: "OFCL",
    Gftc: "GFTC",
    Gftc0623: "GFTC_0623",
    Gftc0902: "GFTC_0902",
} as const;
export type ForecastsConeRequestModel = (typeof ForecastsConeRequestModel)[keyof typeof ForecastsConeRequestModel];
