// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         valid_time_start: "2024-01-15T09:30:00Z",
 *         valid_time_end: "2024-01-15T09:30:00Z"
 *     }
 */
export interface PortfoliosObservationsRequest {
    id?: string | string[];
    variables?: string | string[];
    valid_time_start: string;
    valid_time_end: string;
}
