// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         x: 1,
 *         y: 1,
 *         z: 1,
 *         country: "country"
 *     }
 */
export interface PortfoliosFeaturesRequest {
    x?: number;
    y?: number;
    z?: number;
    country?: string;
}
