// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         time: "2024-01-15T09:30:00Z"
 *     }
 */
export interface PortfoliosInitTimeRequest {
    time: string;
}
