// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: ["id"],
 *         variables: ["variables"],
 *         init_time: "2024-01-15T09:30:00Z"
 *     }
 */
export interface PortfoliosForecastsRequest {
    id?: string | string[];
    variables?: string | string[];
    init_time: string;
}
