// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../../../core/headers.js";
import * as core from "../../../../../../core/index.js";
import * as environments from "../../../../../../environments.js";
import * as errors from "../../../../../../errors/index.js";
import * as Earth from "../../../../../index.js";
import { Past } from "../resources/past/client/Client.js";
import { Personalized } from "../resources/personalized/client/Client.js";
import { Regional } from "../resources/regional/client/Client.js";

export declare namespace Experimental {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class Experimental {
    protected readonly _options: Experimental.Options;
    protected _regional: Regional | undefined;
    protected _personalized: Personalized | undefined;
    protected _past: Past | undefined;

    constructor(_options: Experimental.Options = {}) {
        this._options = _options;
    }

    public get regional(): Regional {
        return (this._regional ??= new Regional(this._options));
    }

    public get personalized(): Personalized {
        return (this._personalized ??= new Personalized(this._options));
    }

    public get past(): Past {
        return (this._past ??= new Past(this._options));
    }

    /**
     * Get hourly weather forecast for a specific location and time
     *
     * @param {Earth.weather.ExperimentalExtendedRequest} request
     * @param {Experimental.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Earth.UnprocessableEntityError}
     *
     * @example
     *     await client.weather.experimental.extended({
     *         latitude: 47.6061,
     *         longitude: -122.3328,
     *         timezone: "local",
     *         units: "metric"
     *     })
     */
    public extended(
        request: Earth.weather.ExperimentalExtendedRequest,
        requestOptions?: Experimental.RequestOptions,
    ): core.HttpResponsePromise<Earth.HourlyWeatherResponse> {
        return core.HttpResponsePromise.fromPromise(this.__extended(request, requestOptions));
    }

    private async __extended(
        request: Earth.weather.ExperimentalExtendedRequest,
        requestOptions?: Experimental.RequestOptions,
    ): Promise<core.WithRawResponse<Earth.HourlyWeatherResponse>> {
        const { latitude, longitude, timezone, units } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams.latitude = latitude.toString();
        _queryParams.longitude = longitude.toString();
        if (timezone != null) {
            _queryParams.timezone = timezone;
        }

        if (units != null) {
            _queryParams.units = units;
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.EarthEnvironment.Production,
                "experimental/extended",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Earth.HourlyWeatherResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Earth.UnprocessableEntityError(
                        _response.error.body as Earth.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.EarthError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.EarthError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.EarthTimeoutError("Timeout exceeded when calling GET /experimental/extended.");
            case "unknown":
                throw new errors.EarthError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders(): Promise<Record<string, string | undefined>> {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { "X-API-KEY": apiKeyValue };
    }
}
