// This file was auto-generated by Fern from our API Definition.

import * as Earth from "../../src/api/index";
import { EarthClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("PortfoliosClient", () => {
    test("features (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new EarthClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            bbox: [{ key: "value" }],
            type: "FeatureCollection",
            features: [
                {
                    type: "Feature",
                    geometry: { type: "GeometryCollection", geometries: [{ type: "LineString", coordinates: [[]] }] },
                    properties: { key: "value" },
                    id: 1,
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/portfolios/my-portfolio/features")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.portfolios.features("my-portfolio", {
            x: 1,
            y: 1,
            z: 1,
            country: "country",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("features (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new EarthClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/portfolios/portfolio_id/features")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.portfolios.features("portfolio_id");
        }).rejects.toThrow(Earth.UnauthorizedError);
    });

    test("features (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new EarthClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/portfolios/portfolio_id/features")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.portfolios.features("portfolio_id");
        }).rejects.toThrow(Earth.NotFoundError);
    });

    test("features (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new EarthClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/portfolios/portfolio_id/features")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.portfolios.features("portfolio_id");
        }).rejects.toThrow(Earth.UnprocessableEntityError);
    });

    test("features (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new EarthClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/portfolios/portfolio_id/features")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.portfolios.features("portfolio_id");
        }).rejects.toThrow(Earth.InternalServerError);
    });

    test("forecasts (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new EarthClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            bbox: [{ key: "value" }],
            type: "FeatureCollection",
            features: [
                {
                    type: "Feature",
                    geometry: { type: "GeometryCollection", geometries: [{ type: "LineString", coordinates: [[]] }] },
                    properties: { datetimes: ["2024-01-15T09:30:00Z"], static: { key: "value" } },
                    id: 1,
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/portfolios/my-portfolio/forecasts")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.portfolios.forecasts("my-portfolio", {
            id: ["station_A", "station_B"],
            variables: ["temperature", "wind_speed"],
            init_time: "2024-01-15T09:30:00Z",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("forecasts (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new EarthClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/portfolios/portfolio_id/forecasts")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.portfolios.forecasts("portfolio_id", {
                init_time: "2024-01-15T09:30:00Z",
            });
        }).rejects.toThrow(Earth.UnauthorizedError);
    });

    test("forecasts (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new EarthClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/portfolios/portfolio_id/forecasts")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.portfolios.forecasts("portfolio_id", {
                init_time: "2024-01-15T09:30:00Z",
            });
        }).rejects.toThrow(Earth.NotFoundError);
    });

    test("forecasts (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new EarthClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/portfolios/portfolio_id/forecasts")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.portfolios.forecasts("portfolio_id", {
                init_time: "2024-01-15T09:30:00Z",
            });
        }).rejects.toThrow(Earth.UnprocessableEntityError);
    });

    test("forecasts (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new EarthClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/portfolios/portfolio_id/forecasts")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.portfolios.forecasts("portfolio_id", {
                init_time: "2024-01-15T09:30:00Z",
            });
        }).rejects.toThrow(Earth.InternalServerError);
    });

    test("observations (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new EarthClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            bbox: [{ key: "value" }],
            type: "FeatureCollection",
            features: [
                {
                    type: "Feature",
                    geometry: { type: "GeometryCollection", geometries: [{ type: "LineString", coordinates: [[]] }] },
                    properties: { datetimes: ["2024-01-15T09:30:00Z"], static: { key: "value" } },
                    id: 1,
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/portfolios/my-portfolio/observations")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.portfolios.observations("my-portfolio", {
            id: ["station_A", "station_B"],
            variables: ["temperature", "wind_speed"],
            valid_time_start: "2024-01-15T09:30:00Z",
            valid_time_end: "2024-01-15T09:30:00Z",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("observations (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new EarthClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/portfolios/portfolio_id/observations")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.portfolios.observations("portfolio_id", {
                valid_time_start: "2024-01-15T09:30:00Z",
                valid_time_end: "2024-01-15T09:30:00Z",
            });
        }).rejects.toThrow(Earth.UnauthorizedError);
    });

    test("observations (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new EarthClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/portfolios/portfolio_id/observations")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.portfolios.observations("portfolio_id", {
                valid_time_start: "2024-01-15T09:30:00Z",
                valid_time_end: "2024-01-15T09:30:00Z",
            });
        }).rejects.toThrow(Earth.NotFoundError);
    });

    test("observations (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new EarthClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/portfolios/portfolio_id/observations")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.portfolios.observations("portfolio_id", {
                valid_time_start: "2024-01-15T09:30:00Z",
                valid_time_end: "2024-01-15T09:30:00Z",
            });
        }).rejects.toThrow(Earth.UnprocessableEntityError);
    });

    test("observations (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new EarthClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/portfolios/portfolio_id/observations")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.portfolios.observations("portfolio_id", {
                valid_time_start: "2024-01-15T09:30:00Z",
                valid_time_end: "2024-01-15T09:30:00Z",
            });
        }).rejects.toThrow(Earth.InternalServerError);
    });

    test("init_time (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new EarthClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = "2024-01-15T09:30:00Z";

        server
            .mockEndpoint()
            .get("/portfolios/my-portfolio/init_time")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.portfolios.initTime("my-portfolio", {
            time: "2024-01-15T09:30:00Z",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("init_time (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new EarthClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/portfolios/portfolio_id/init_time")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.portfolios.initTime("portfolio_id", {
                time: "2024-01-15T09:30:00Z",
            });
        }).rejects.toThrow(Earth.UnauthorizedError);
    });

    test("init_time (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new EarthClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/portfolios/portfolio_id/init_time")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.portfolios.initTime("portfolio_id", {
                time: "2024-01-15T09:30:00Z",
            });
        }).rejects.toThrow(Earth.NotFoundError);
    });

    test("init_time (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new EarthClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/portfolios/portfolio_id/init_time")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.portfolios.initTime("portfolio_id", {
                time: "2024-01-15T09:30:00Z",
            });
        }).rejects.toThrow(Earth.UnprocessableEntityError);
    });

    test("init_time (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new EarthClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/portfolios/portfolio_id/init_time")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.portfolios.initTime("portfolio_id", {
                time: "2024-01-15T09:30:00Z",
            });
        }).rejects.toThrow(Earth.InternalServerError);
    });
});
