// This file was auto-generated by Fern from our API Definition.

import * as Earth from "../../src/api/index";
import { EarthClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("Portfolios", () => {
    test("features (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new EarthClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            bbox: [{ key: "value" }],
            type: "FeatureCollection",
            features: [
                {
                    type: "Feature",
                    geometry: { type: "GeometryCollection", geometries: [{ type: "LineString", coordinates: [[]] }] },
                    properties: { key: "value" },
                    id: 1,
                },
            ],
        };
        server
            .mockEndpoint()
            .get("/portfolios/portfolio_id/features")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.portfolios.features("portfolio_id", {
            x: 1,
            y: 1,
            z: 1,
            country: "country",
        });
        expect(response).toEqual({
            bbox: [
                {
                    key: "value",
                },
            ],
            type: "FeatureCollection",
            features: [
                {
                    type: "Feature",
                    geometry: {
                        type: "GeometryCollection",
                        geometries: [
                            {
                                type: "LineString",
                                coordinates: [[]],
                            },
                        ],
                    },
                    properties: {
                        key: "value",
                    },
                    id: 1,
                },
            ],
        });
    });

    test("features (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new EarthClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .get("/portfolios/portfolio_id/features")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.portfolios.features("portfolio_id");
        }).rejects.toThrow(Earth.UnprocessableEntityError);
    });

    test("forecasts (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new EarthClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            bbox: [{ key: "value" }],
            type: "FeatureCollection",
            features: [
                {
                    type: "Feature",
                    geometry: { type: "GeometryCollection", geometries: [{ type: "LineString", coordinates: [[]] }] },
                    properties: { datetimes: ["2024-01-15T09:30:00Z"], static: { key: "value" } },
                    id: 1,
                },
            ],
        };
        server
            .mockEndpoint()
            .get("/portfolios/portfolio_id/forecasts")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.portfolios.forecasts("portfolio_id", {
            init_time: "2024-01-15T09:30:00Z",
        });
        expect(response).toEqual({
            bbox: [
                {
                    key: "value",
                },
            ],
            type: "FeatureCollection",
            features: [
                {
                    type: "Feature",
                    geometry: {
                        type: "GeometryCollection",
                        geometries: [
                            {
                                type: "LineString",
                                coordinates: [[]],
                            },
                        ],
                    },
                    properties: {
                        datetimes: ["2024-01-15T09:30:00Z"],
                        static: {
                            key: "value",
                        },
                    },
                    id: 1,
                },
            ],
        });
    });

    test("forecasts (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new EarthClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .get("/portfolios/portfolio_id/forecasts")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.portfolios.forecasts("portfolio_id", {
                init_time: "2024-01-15T09:30:00Z",
            });
        }).rejects.toThrow(Earth.UnprocessableEntityError);
    });

    test("observations (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new EarthClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            bbox: [{ key: "value" }],
            type: "FeatureCollection",
            features: [
                {
                    type: "Feature",
                    geometry: { type: "GeometryCollection", geometries: [{ type: "LineString", coordinates: [[]] }] },
                    properties: { datetimes: ["2024-01-15T09:30:00Z"], static: { key: "value" } },
                    id: 1,
                },
            ],
        };
        server
            .mockEndpoint()
            .get("/portfolios/portfolio_id/observations")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.portfolios.observations("portfolio_id", {
            valid_time_start: "2024-01-15T09:30:00Z",
            valid_time_end: "2024-01-15T09:30:00Z",
        });
        expect(response).toEqual({
            bbox: [
                {
                    key: "value",
                },
            ],
            type: "FeatureCollection",
            features: [
                {
                    type: "Feature",
                    geometry: {
                        type: "GeometryCollection",
                        geometries: [
                            {
                                type: "LineString",
                                coordinates: [[]],
                            },
                        ],
                    },
                    properties: {
                        datetimes: ["2024-01-15T09:30:00Z"],
                        static: {
                            key: "value",
                        },
                    },
                    id: 1,
                },
            ],
        });
    });

    test("observations (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new EarthClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .get("/portfolios/portfolio_id/observations")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.portfolios.observations("portfolio_id", {
                valid_time_start: "2024-01-15T09:30:00Z",
                valid_time_end: "2024-01-15T09:30:00Z",
            });
        }).rejects.toThrow(Earth.UnprocessableEntityError);
    });

    test("init_time (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new EarthClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = "2024-01-15T09:30:00Z";
        server
            .mockEndpoint()
            .get("/portfolios/portfolio_id/init_time")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.portfolios.initTime("portfolio_id", {
            time: "2024-01-15T09:30:00Z",
        });
        expect(response).toEqual("2024-01-15T09:30:00Z");
    });

    test("init_time (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new EarthClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .get("/portfolios/portfolio_id/init_time")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.portfolios.initTime("portfolio_id", {
                time: "2024-01-15T09:30:00Z",
            });
        }).rejects.toThrow(Earth.UnprocessableEntityError);
    });
});
