// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../../../core/headers.js";
import * as core from "../../../../../../core/index.js";
import * as environments from "../../../../../../environments.js";
import * as errors from "../../../../../../errors/index.js";
import * as Earth from "../../../../../index.js";

export declare namespace Forecasts {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class Forecasts {
    protected readonly _options: Forecasts.Options;

    constructor(_options: Forecasts.Options = {}) {
        this._options = _options;
    }

    /**
     * Query the available cyclone forecasts for a particular time
     *
     * @param {Earth.cyclones.ForecastsListRequest} request
     * @param {Forecasts.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Earth.UnprocessableEntityError}
     *
     * @example
     *     await client.cyclones.forecasts.list({
     *         time: "2024-01-15T09:30:00Z",
     *         min_storm_category: 1,
     *         model: "OFCL"
     *     })
     */
    public list(
        request: Earth.cyclones.ForecastsListRequest = {},
        requestOptions?: Forecasts.RequestOptions,
    ): core.HttpResponsePromise<Earth.CycloneForecastResponse[]> {
        return core.HttpResponsePromise.fromPromise(this.__list(request, requestOptions));
    }

    private async __list(
        request: Earth.cyclones.ForecastsListRequest = {},
        requestOptions?: Forecasts.RequestOptions,
    ): Promise<core.WithRawResponse<Earth.CycloneForecastResponse[]>> {
        const { time, min_storm_category: minStormCategory, basin_ids: basinIds, model } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (time != null) {
            _queryParams.time = time;
        }

        if (minStormCategory != null) {
            _queryParams.min_storm_category = minStormCategory.toString();
        }

        if (basinIds != null) {
            if (Array.isArray(basinIds)) {
                _queryParams.basin_ids = basinIds.map((item) => item);
            } else {
                _queryParams.basin_ids = basinIds;
            }
        }

        if (model != null) {
            _queryParams.model = model;
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.EarthEnvironment.Production,
                "cyclones/forecasts",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Earth.CycloneForecastResponse[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Earth.UnprocessableEntityError(
                        _response.error.body as Earth.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.EarthError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.EarthError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.EarthTimeoutError("Timeout exceeded when calling GET /cyclones/forecasts.");
            case "unknown":
                throw new errors.EarthError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get cyclone tracks in GeoJSON (MF-GeoJSON) format
     *
     * @param {string} stormId
     * @param {Earth.cyclones.ForecastsTrackRequest} request
     * @param {Forecasts.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Earth.UnprocessableEntityError}
     *
     * @example
     *     await client.cyclones.forecasts.track("storm_id", {
     *         time: "2024-01-15T09:30:00Z",
     *         max_lead_time: "max_lead_time",
     *         model: "OFCL"
     *     })
     */
    public track(
        stormId: string,
        request: Earth.cyclones.ForecastsTrackRequest = {},
        requestOptions?: Forecasts.RequestOptions,
    ): core.HttpResponsePromise<Earth.FeatureCollection> {
        return core.HttpResponsePromise.fromPromise(this.__track(stormId, request, requestOptions));
    }

    private async __track(
        stormId: string,
        request: Earth.cyclones.ForecastsTrackRequest = {},
        requestOptions?: Forecasts.RequestOptions,
    ): Promise<core.WithRawResponse<Earth.FeatureCollection>> {
        const { time, max_lead_time: maxLeadTime, model } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (time != null) {
            _queryParams.time = time;
        }

        if (maxLeadTime != null) {
            _queryParams.max_lead_time = maxLeadTime;
        }

        if (model != null) {
            _queryParams.model = model;
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.EarthEnvironment.Production,
                `cyclones/forecasts/${core.url.encodePathParam(stormId)}/track`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Earth.FeatureCollection, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Earth.UnprocessableEntityError(
                        _response.error.body as Earth.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.EarthError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.EarthError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.EarthTimeoutError(
                    "Timeout exceeded when calling GET /cyclones/forecasts/{storm_id}/track.",
                );
            case "unknown":
                throw new errors.EarthError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get cyclone forecast cone in GeoJSON format
     *
     * @param {string} stormId
     * @param {Earth.cyclones.ForecastsConeRequest} request
     * @param {Forecasts.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Earth.UnprocessableEntityError}
     *
     * @example
     *     await client.cyclones.forecasts.cone("storm_id", {
     *         time: "2024-01-15T09:30:00Z",
     *         max_lead_time: "max_lead_time",
     *         smooth_cone: true,
     *         model: "OFCL"
     *     })
     */
    public cone(
        stormId: string,
        request: Earth.cyclones.ForecastsConeRequest = {},
        requestOptions?: Forecasts.RequestOptions,
    ): core.HttpResponsePromise<Earth.FeatureCollection> {
        return core.HttpResponsePromise.fromPromise(this.__cone(stormId, request, requestOptions));
    }

    private async __cone(
        stormId: string,
        request: Earth.cyclones.ForecastsConeRequest = {},
        requestOptions?: Forecasts.RequestOptions,
    ): Promise<core.WithRawResponse<Earth.FeatureCollection>> {
        const { time, max_lead_time: maxLeadTime, smooth_cone: smoothCone, model } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (time != null) {
            _queryParams.time = time;
        }

        if (maxLeadTime != null) {
            _queryParams.max_lead_time = maxLeadTime;
        }

        if (smoothCone != null) {
            _queryParams.smooth_cone = smoothCone.toString();
        }

        if (model != null) {
            _queryParams.model = model;
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.EarthEnvironment.Production,
                `cyclones/forecasts/${core.url.encodePathParam(stormId)}/cone`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Earth.FeatureCollection, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Earth.UnprocessableEntityError(
                        _response.error.body as Earth.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.EarthError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.EarthError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.EarthTimeoutError(
                    "Timeout exceeded when calling GET /cyclones/forecasts/{storm_id}/cone.",
                );
            case "unknown":
                throw new errors.EarthError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders(): Promise<Record<string, string | undefined>> {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { "X-API-KEY": apiKeyValue };
    }
}
