// This file was auto-generated by Fern from our API Definition.

import type * as Earth from "../../../../../../index.js";

/**
 * @example
 *     {
 *         latitude: 47.6061,
 *         longitude: -122.3328,
 *         timezone: "local",
 *         units: "metric"
 *     }
 */
export interface ForecastDailyRequest {
    latitude: number;
    longitude: number;
    timezone?: "local";
    units?: Earth.Units;
}
