// This file was auto-generated by Fern from our API Definition.

import type * as Earth from "../../../../../../index.js";

/**
 * @example
 *     {
 *         latitude: 47.6061,
 *         longitude: -122.3328,
 *         timezone: "local",
 *         units: "metric",
 *         include_past: true
 *     }
 */
export interface ForecastHourlyRequest {
    latitude: number;
    longitude: number;
    timezone?: Earth.Timezone;
    units?: Earth.Units;
    include_past?: boolean;
}
