// This file was auto-generated by Fern from our API Definition.

import { CyclonesClient } from "./api/resources/cyclones/client/Client.js";
import { PortfoliosClient } from "./api/resources/portfolios/client/Client.js";
import { WeatherClient } from "./api/resources/weather/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";
import * as core from "./core/index.js";

export declare namespace EarthClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class EarthClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<EarthClient.Options>;
    protected _portfolios: PortfoliosClient | undefined;
    protected _cyclones: CyclonesClient | undefined;
    protected _weather: WeatherClient | undefined;

    constructor(options: EarthClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get portfolios(): PortfoliosClient {
        return (this._portfolios ??= new PortfoliosClient(this._options));
    }

    public get cyclones(): CyclonesClient {
        return (this._cyclones ??= new CyclonesClient(this._options));
    }

    public get weather(): WeatherClient {
        return (this._weather ??= new WeatherClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
                getAuthHeaders: async () => (await this._options.authProvider.getAuthRequest()).headers,
            },
            requestOptions,
        );
    }
}
