/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Forecasts } from "./api/resources/forecasts/client/Client";

export declare namespace SilurianClient {
    interface Options {
        environment?: core.Supplier<environments.SilurianEnvironment | string>;
        apiKey: core.Supplier<string>;
    }

    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

export class SilurianClient {
    protected _forecasts: Forecasts | undefined;

    constructor(protected readonly _options: SilurianClient.Options) {}

    public get forecasts(): Forecasts {
        return (this._forecasts ??= new Forecasts(this._options));
    }
}
