// This file was auto-generated by Fern from our API Definition.

export const EarthEnvironment = {
    Production: "https://earth.weather.silurian.ai/api/v1",
} as const;

export type EarthEnvironment = typeof EarthEnvironment.Production;
