/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const SilurianEnvironment = {
    Production: "https://earth.weather.silurian.ai",
} as const;

export type SilurianEnvironment = typeof SilurianEnvironment.Production;
