// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../../../../../BaseClient.js";
import {
    type NormalizedClientOptionsWithAuth,
    normalizeClientOptionsWithAuth,
} from "../../../../../../../../BaseClient.js";
import { RegionalClient } from "../resources/regional/client/Client.js";

export declare namespace PastClient {
    export type Options = BaseClientOptions;
}

export class PastClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<PastClient.Options>;
    protected _regional: RegionalClient | undefined;

    constructor(options: PastClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get regional(): RegionalClient {
        return (this._regional ??= new RegionalClient(this._options));
    }
}
