/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../../../../../environments";
import * as core from "../../../../../../../../core";
import { Regional } from "../resources/regional/client/Client";

export declare namespace Past {
    export interface Options {
        environment?: core.Supplier<environments.EarthEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey: core.Supplier<string>;
    }
}

export class Past {
    protected _regional: Regional | undefined;

    constructor(protected readonly _options: Past.Options) {}

    public get regional(): Regional {
        return (this._regional ??= new Regional(this._options));
    }
}
