// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../../../../../BaseClient.js";
import { Regional } from "../resources/regional/client/Client.js";

export declare namespace Past {
    export interface Options extends BaseClientOptions {}
}

export class Past {
    protected readonly _options: Past.Options;
    protected _regional: Regional | undefined;

    constructor(_options: Past.Options = {}) {
        this._options = _options;
    }

    public get regional(): Regional {
        return (this._regional ??= new Regional(this._options));
    }
}
