/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Earth from "../../../../../../../../index";

/**
 * @example
 *     {
 *         latitude: 47.6061,
 *         longitude: -122.3328,
 *         time: "2024-01-01T00:00:00Z"
 *     }
 */
export interface ForecastHourlyRequest {
    latitude: number;
    longitude: number;
    time: string;
    timezone?: Earth.Timezone;
    units?: Earth.Units;
    include_past?: boolean;
}
