// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { ForecastsClient } from "../resources/forecasts/client/Client.js";

export declare namespace CyclonesClient {
    export type Options = BaseClientOptions;
}

export class CyclonesClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<CyclonesClient.Options>;
    protected _forecasts: ForecastsClient | undefined;

    constructor(options: CyclonesClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get forecasts(): ForecastsClient {
        return (this._forecasts ??= new ForecastsClient(this._options));
    }
}
