// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../BaseClient.js";
import { Forecasts } from "../resources/forecasts/client/Client.js";

export declare namespace Cyclones {
    export interface Options extends BaseClientOptions {}
}

export class Cyclones {
    protected readonly _options: Cyclones.Options;
    protected _forecasts: Forecasts | undefined;

    constructor(_options: Cyclones.Options = {}) {
        this._options = _options;
    }

    public get forecasts(): Forecasts {
        return (this._forecasts ??= new Forecasts(this._options));
    }
}
